FROM alpine:latest
RUN addgroup -S nginx1 && adduser -S nginx1 nginx1
# RUN apt-get update \
#     && apt-get nginx
CMD ["/bin/sh"]
# CMD ["sleep","2000"]


# FROM nginx
# RUN addgroup nginx1 && useradd nginx1 nginx1
# RUN echo "Hello" > /tmp/hello.txt
# # Run chown -R nginx1:nginx1 /opt
# CMD [ "nginx" , "-g" , "daemon off;" ]
# USER nginx1


# FROM busybox:stable
# CMD ["sh"]